---
- name: Provision Image Dinivas Base Centos7
  hosts: packer-dinivas-base
  become: true
  vars:
    consul_user: consul
    consul_group: bin
    consul_config_path: "/etc/consul"
    consul_configd_path: "{{ consul_config_path }}/consul.d"
    unbound_configd_path: "/etc/unbound/conf.d"
    consul_domain: dinivas
  roles:
    - role: viasite-ansible.zsh
    - role: cloudalchemy.node-exporter
    - role: dinivas.filebeat
    - role: dinivas.consul
      consul_node_role: server
      consul_bootstrap_expect: true
      consul_bootstrap_expect_value: 1
      consul_datacenter: dinivas-dc
      consul_ui: true
      consul_client_address: '0.0.0.0'
      consul_encrypt_enable: false
      consul_install_upgrade: true

  tasks:
    - name: Copy node_exporter consul service definition
      template:
        src: "{{ playbook_dir }}/templates/node_exporter-service.json.j2"
        dest: "{{ consul_configd_path }}/node_exporter-service.json"
        mode: 0644
        owner: "{{ consul_user }}"
        group: "{{ consul_group }}"
      notify: restart consul
    - name: Install DNS resolver (Unbound)
      package:
        name: unbound
        state: present
    - name: Create unbound log file
      file:
        path: "{{ item }}"
        state: touch
        owner: unbound
        group: unbound
        mode: '0755'
      with_items:
        - /var/log/unbound.log
      notify: restart unbound
    - name: Copy unbound local Consul configuration
      template:
        src: "{{ playbook_dir }}/templates/local-consul.conf.j2"
        dest: "{{ unbound_configd_path }}/local-consul.conf"
        mode: 0644
      notify: restart unbound
    - name: Add line to include all unbound conf files
      lineinfile:
        dest: /etc/unbound/unbound.conf
        state: present
        line: 'include: "{{ unbound_configd_path }}/*.conf"'
        insertafter: EOF
    - name: Add localhost to resolv.conf for local resolution
      lineinfile:
        path: /etc/resolv.conf
        state: present
        line: 'nameserver 127.0.0.1'
        insertbefore: BOF
      ignore_errors: true
    - name: Start unbound service
      service:
        name: unbound
        enabled: yes
        state: started
      become: true

  handlers:
    - name: restart unbound
      service:
        name: unbound
        state: restarted
      become: true

